### ISSUE TITLE
Support for Firefox webextension

### ISSUE THREAD

**Issue by juliandescottes** [melink14/rikaikun#132]
With Firefox 57, rikaichan will not be supported anymore. 

This would be a good occasion to bring this webextension to Firefox. After a few fixes, most of it seems to work. Will submit a PR shortly.

**Comment by birtles** [comment]
I am working on a fork that does this: https://github.com/birtles/rikaichamp

Unfortunately I've got a bit bogged down rewriting most of the code in the process.

**Comment by juliandescottes** [comment]
Great @birtles ! 

Even though I got the webextension to work on Firefox, it keeps showing up the wrong information and I didn't have the time to actually debug the issue. I should probably push my branch anyway in case someone can figure out what is wrong.

**Comment by juliandescottes** [comment]
Here is my branch : 
https://github.com/juliandescottes/rikaikun/tree/firefox

And the diff ignoring whitespace (my editor trimmed a lot of line ending whitespace ...):
https://github.com/juliandescottes/rikaikun/commit/b88370e858898849aee4da67c75ceab5f6b42cc0?diff=split&w=1

**Comment by birtles** [comment]
Yeah, it works correctly for me. I know I encountered some issues with wrong information due to incorrect line endings on the data files which were throwing the indices out (perhaps a result of the code.google.com → github conversion).

I've fixed a _lot_ of issues since that and added automated testing for a lot of the complicated parts. I'll try to finish the couple of parts I'm currently rewriting and then publish soon.

**Comment by bomjacob** [comment]
If either of you guys need help with porting I'll be happy to help out :) @birtles @juliandescottes

**Comment by birtles** [comment]
I've published an initial version now:
https://addons.mozilla.org/en-US/firefox/addon/rikaichamp/

There are still a number of features missing (and probably a number of new bugs!) but I'll add them one by one.

**Comment by melink14** [comment]
It looks like with the new web extension API the same code should work for many modern browsers. I assume there are some browser specific APIs that prevent complete code sharing but it might be good to set something up where common fixes can be easily pulled into both versions.

**Comment by birtles** [comment]
Yes, I should make rikaichamp available for Chrome and Edge too. I simply haven't yet because I'm afraid of all the new issues that will be filed! I was planning to convert the dictionary to a JSON-based format that can be incrementally updated before porting this over to Chrome etc. but perhaps I can work on porting in parallel.

**Comment by melink14** [comment]
I'm not talking about about porting rikaichamp as much as preventing skew between the versions. Though I guess we can work independently and merge as we want given they're both open source.

**Comment by birtles** [comment]
Oh, I see. Yeah, unfortunately rikaichamp is a complete rewrite of rikaikun so I'm not sure how practical sharing will be.

**Comment by melink14** [comment]
I wouldn't call a rewrite of rikaikun unfortunate! I did the minimum possible as far as refactors and the code has not aged well.

I'm super impressed with your re-write to Typescript and the addition of tests.

Already, I could merge over improvements you've made (and vice versa for rikaikun features) (or even utils) and that would be super useful but then any improvements made by either party after that would require manual patching to get fixes.

In any case, I'm glad you were able to get it working in firefox and I hope it aids Japanese learners as much as rikaikun has.

**Comment by birtles** [comment]
Thanks Erek! And thanks for all your work on rikaikun!

I think I actually need to at least experiment with getting rikaichamp to work on Chrome just because I need to understand the Chrome DevTools better for work. Hopefully doing that will make the code more re-usable too.

**Comment by Garethp** [comment]
Hey, sorry to butt in. I'm also doing a port of Rikaisama. Unlike @birtles I'm not rewriting it from scratch, but porting code over functionality by functionality and then cleaning up later (Which means my code is still pretty messy). On the other hand, I've made (in my opinion) a few improvements or changes that might be good to implement. For example, I'm keeping my dictionaries in an IndexedDb database using `dixie.js`, and storing the actual data files in a separate repo (so users can have multiple dictionaries and download them as needed). I've also implemented Anki importing and a few other features so far.

I have managed to get the plugin working pretty seemlessly on both Chrome and Firefox. So if you guys are still having trouble porting over, I should be able to offer some insight in how I did it.

**Comment by Garethp** [comment]
I am pretty jealous of your tests and clean code though @birtles. Definitely going to try to achieve something as nice as that when I get the lookup bar and EPWING mode in. If my code didn't need so much cleaning up because it came from Rikaisama I'd ask if you wanted to collaborate on my version instead of working separately!

**Comment by birtles** [comment]
Thanks @Garethp! Yeah, I was thinking about how to share stuff but I don't have a good idea. Just last week I fixed a bunch of deinflection bugs which apparently affect yomichan etc. too (i.e. we're sharing the same bugs).

I've ported Rikaichamp to Chrome but I haven't released it there, mostly because I don't have time to follow up the anticipated additional bug reports.

I'd also like to move to IndexedDB but I'm working (very very slowly) on a sync service so that the data files stay up to date.

EPWING support would be nice. Perhaps there are some modules we can factor out and share?

**Comment by Garethp** [comment]
Would you mind doing a good explanation of the bugs? I'd like to see if they're in mine as well. And since mine comes right from rikaisama, they probably are.

I think the hard part of epwing is going to be getting the epwing lookup executable talking to the add-on, but once that's done it should be easy to make a separate class we can share. I can try to go ahead and do that for my Sanseido mode if you'd like

**Comment by birtles** [comment]
Let's just take zero-EPWING, covert it to rust, then compile it to WebAssembly.
