### ISSUE TITLE
remove pinyin entries

### ISSUE THREAD

**Issue by joegonzalez722** [melink14/rikaikun#383]

**Comment by melink14** [comment]
I think some people (myself included) find them useful as a reference but I assume they're taking up space for you?

Usually, I'd suggest turning them off in the settings but it will reset after restart due to a settings bug: https://github.com/melink14/rikaikun/issues/346

That being said, another option is to think about whether the default for extra kanji information should be all on or mostly off. Might make sense if there was an on installation guide which told people about the options.

**Comment by joegonzalez722** [comment]
I found a solution to this. I just downloaded the code and did the css code "display: none;" for the kanji info.

**Comment by melink14** [comment]
(Isn't that harder than hiding it via the options?)

**Comment by joegonzalez722** [comment]
It is harder for sure, but if you already know a bit about css it is an option.
