### ISSUE TITLE
'Text-To-Speech' feature not working on Brave browser

### ISSUE THREAD

**Issue by fraDeckiGH** [melink14/rikaikun#599]
**Describe the bug**
the rikaikun extension successfully highlights the text but doesn't read it

**To Reproduce**
1. highlight japanese text (kanji/kana)
2. rikaikun extension won't read it out loud

**Expected behavior**
highlighted text being read by some female

**Screenshots**
Not needed.

**System details (OS, browser version, rikaikun version)**

- OS: Windows 10 Pro -> Version 10.0.19043 Build 19043
- Browser Version: 1.26.74
- rikaikun Version: 1.2.6

**Additional context**
Installed from the Chrome Web Store

**Comment by melink14** [comment]
Thanks for the bug report, I don't use Brave and can't say we support it officially but of course it *should* work since it's based on chromium.

I'm not sure exactly why it's not working but it's possible that it's related to this issue: https://community.brave.com/t/select-and-speak-extension-with-brave/45043 mentions that perhaps brave will prompt with a play button initially which then goes away for TTS, but I'm not 100% sure.

Try that out and see what happens; though if it doesn't work there's probably not much I can do.

**Comment by fraDeckiGH** [comment]
I tried, and don't see that prompt. Thanks anyway.

**Comment by melink14** [comment]
Ah, that's too bad. You could also try on normal chrome if possible to see if there's a larger issue but otherwise it will be difficult to work around brave specific issues. 🙇🏾
